[package]
name = "tui-project-manager"
version = "0.1.0"
authors = ["JCodV <154752793+JCodV@users.noreply.github.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
serde = "1.0.217"
serde_json = "1.0.137"
